import Nav from './components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Film Database',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-pink-300 via-pink-300 to-indigo-400`}>

        <Nav/>
      
       <main className='px-4'>
          <div className="flex items-center bg-white mx-auto w-2/4 rounded-lg my-16 p-16">
            <div className="text-2xl font-medium">{children}</div>
          </div>
       </main>
      </body>
    </html>
  )
}
